spring:
  main:
    allow-bean-definition-overriding: true

server:
  port: 7777
invoicing-system:
  database: memory
  database.directory: db
  database.invoices.file: invoices.txt
  database.id.file: id.txt

logging:
  level:
    org:
      springframework:
        boot: TRACE
    pl:
      futurecollars:
        invoicing: WARN
        invoicing.db: DEBUG