spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/invoices-jpa
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false

invoicing-system:
  database: jpa